# Build context for Dockerfile.snapshots (BuildKit reads this file instead of .dockerignore).
.git
**/node_modules
**/dist
**/coverage
**/storybook-static
**/.vite
**/cypress/screenshots
**/cypress/videos
**/cypress/downloads
**/cypress/snapshots
packages/webapp/*
!packages/webapp/package.json
*.md
docker-compose*.yml
