/*
 *    Copyright [2007-2025] [wisemapping]
 *
 *   Licensed under WiseMapping Public License, Version 1.0 (the "License").
 *   It is basically the Apache License, Version 2.0 (the "License") plus the
 *   "powered by wisemapping" text requirement on every single page;
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the license at
 *
 *       https://github.com/wisemapping/wisemapping-open-source/blob/main/LICENSE.md
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

import { execFileSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';

type Source = Record<string, { defaultMessage: string }>;
type Compiled = Record<string, { type: number; value: string }[]>;

const root = path.resolve(__dirname, '../../..');
const readJson = <T>(file: string): T =>
  JSON.parse(fs.readFileSync(path.resolve(root, file), 'utf8')) as T;

const en = readJson<Source>('lang/en.json');
const compiledEn = readJson<Compiled>('src/compiled-lang/en.json');

/**
 * lang/en.json is generated by `i18n:extract` and compiled by `i18n:compile`; English users get
 * the compiled copy, which overrides each defaultMessage in the source. These keep the source,
 * en.json and its compiled copy from drifting apart again: after changing a message, run
 * `yarn i18n:extract && yarn i18n:compile`.
 */
describe('English messages', () => {
  test('the compiled messages are exactly lang/en.json', () => {
    expect(Object.keys(compiledEn).sort()).toEqual(Object.keys(en).sort());
  });

  test('lang/en.json is what i18n:extract produces from the source', () => {
    // The same command as the package's i18n:extract script, into a scratch file.
    const script = readJson<{ scripts: Record<string, string> }>('package.json').scripts[
      'i18n:extract'
    ];
    const out = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'i18n-')), 'en.json');
    execFileSync('sh', ['-c', `${script.replace('lang/en.json', out)}`], {
      cwd: root,
      env: {
        ...process.env,
        PATH: `${path.resolve(root, '../../node_modules/.bin')}:${process.env.PATH}`,
      },
      stdio: 'pipe',
    });
    expect(JSON.parse(fs.readFileSync(out, 'utf8'))).toEqual(en);
  }, 60000);

  test('keeps the space after the duplicated map prefix', () => {
    // The duplicate dialog builds its title as `${prefix}${title}`.
    expect(en['duplicate.copy-prefix'].defaultMessage).toBe('Copy of ');
    expect(compiledEn['duplicate.copy-prefix']).toEqual([{ type: 0, value: 'Copy of ' }]);
  });
});
